  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: mosquitto-data
    namespace: solarbita
  spec:
    capacity:
      storage: 50Mi
    accessModes:
      - ReadWriteOnce
    nfs:
      path: /mnt/fileserv/kubernetes/mosquitto/data