apiVersion: v1
kind: ReplicationController
metadata:
  name: mosquitto-v0
  namespace: solarbita
  labels:
    app: mosquitto
    version: v0
spec:
  replicas: 1
  selector:
    app: mosquitto
    version: v0
  template:
    metadata:
      labels:
        app: mosquitto
        version: v0
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 0.5
            memory: 500Mi
        volumeMounts:
        - name: mosquitto
          mountPath: /etc/mosquitto
        ports:
        - containerPort: 8883
          name: mosquitto
      volumes:
      - name: mosquitto
        persistentVolumeClaim:
          claimName: mosquitto
