  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: mosquitto
    namespace: solarbita
  spec:
    capacity:
      storage: 15Mi
    accessModes:
      - ReadOnlyMany
    nfs:
      path: /mnt/fileserv/kubernetes/mosquitto/config
